export enum ErrorCodes {
  BAD_REQUEST = 'bad_request',
  UNAUTHORIZED = 'unauthorized',
  PAYMENT_REQUIRED = 'payment_required',
  FORBIDDEN = 'forbidden',
  NOT_FOUND = 'not_found',
  METHOD_NOT_ALLOWED = 'method_not_allowed',
  NOT_ACCEPTABLE = 'not_acceptable',
  PROXY_AUTHENTICATION_REQUIRED = 'proxy_authentication_required',
  REQUEST_TIMEOUT = 'request_timeout',
  CONFLICT = 'conflict',
  GONE = 'gone',
  LENGTH_REQUIRED = 'length_required',
  PRECONDITION_FAILED = 'precondition_failed',
  PAYLOAD_TOO_LARGE = 'payload_too_large',
  URI_TOO_LONG = 'uri_too_long',
  UNSUPPORTED_MEDIA_TYPE = 'unsupported_media_type',
  RANGE_NOT_SATISFIABLE = 'range_not_satisfiable',
  EXPECTATION_FAILED = 'expectation_failed',
  MISDIRECTED_REQUESt = 'misdirected_request',
  TOO_EARLY = 'too_early',
  UPGRADE_REQUIRED = 'upgrade_required',
  PRECONDITION_REQUIRED = 'precondition_required',
  TOO_MANY_REQUESTS = 'too_many_requests',

  INTERNAL_SERVER_ERROR = 'internal_server_error',
  NOT_IMPLEMENTED = 'not_implemented',
  BAD_GATEWAY = 'bad_gateway',
  SERVICE_UNAVAILABLE = 'service_unavailable',
  GATEWAY_TIMEOUT = 'gateway_timeout',
}